# @package _global_
defaults:
  - _self_

openai_api_key:
model_name: ClinicalCamel-70B-GPTQ
max_context_length: 4096
exllama: True

system_tag_start: ""
system_tag_end: ""

user_tag_start: "\n\n### User: "
user_tag_end: ""

ai_tag_start: "\n\n### Assistant: "
ai_tag_end: ""

stop_words:
 - "###"
 - "User:"
 - "Assistant:"