# @package _global_
defaults:
  - _self_

openai_api_key:
model_name: Llama2-70B-OASST-SFT-v10-GPTQ
max_context_length: 4096
exllama: True

system_tag_start: "<|im_start|>system\n"
system_tag_end: "<|im_end|>\n"

user_tag_start: "<|im_start|>user\n"
user_tag_end: "<|im_end|>\n"

ai_tag_start: "<|im_start|>assistant\n"
ai_tag_end: "<|im_end|>\n"

stop_words:
 - "<|im_start|>"
 - "<|im_end|>"