# @package _global_
defaults:
  - _self_

openai_api_key: sk-111111111111111111111111111111111111111111111111
openai_api_base: http://127.0.0.1:5001/v1

model_name: Meta-Llama-3-70B-Instruct-GGUF
max_context_length: 8192
tokenizer: Xenova/llama3-tokenizer-new
exllama: False

system_tag_start: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n"
system_tag_end: "<|eot_id|>"

user_tag_start: "<|start_header_id|>user<|end_header_id|>\n\n"
user_tag_end: "<|eot_id|>"

ai_tag_start: "<|start_header_id|>assistant<|end_header_id|>\n\n"
ai_tag_end: "<|eot_id|>"

stop_words:
 - "<|start_header_id|>"
 - "<|end_header_id|>"
 - "<|eot_id|>"


