# @package _global_
defaults:
  - _self_

openai_api_key: ollama
openai_api_base: http://localhost:11434/v1/

model_name: ollama-llama3.1:70b-instruct-q4_0-8k
max_context_length: 8192
tokenizer: Xenova/Meta-Llama-3.1-Tokenizer
exllama: False

system_tag_start: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n"
system_tag_end: "<|eot_id|>"

user_tag_start: "<|start_header_id|>user<|end_header_id|>\n\n"
user_tag_end: "<|eot_id|>"

ai_tag_start: "<|start_header_id|>assistant<|end_header_id|>\n\n"
ai_tag_end: "<|eot_id|>"

stop_words:
 - "<|start_header_id|>"
 - "<|end_header_id|>"
 - "<|eot_id|>"


